name: Setup Python
description: Setup Python


runs:
  using: "composite"
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - run: uv install
      shell: bash