name: Setup Python
description: Setup Python


runs:
  using: "composite"

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - run: uv sync --index-url https://pypi.org/simple/
      shell: bash